version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    restart: always
    container_name: appdb
    tty: true
    volumes:
      - ./mysql/:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=appdb
      - MYSQL_ROOT_PASSWORD=root123
    networks:
      - node_network
    healthcheck:
        test: "/usr/bin/mysql --user=root --password=root123 --execute \"SHOW DATABASES;\""
        interval: 20s
        timeout: 20s
        retries: 10
  nginx:
    image: nginx:1.15
    container_name: appnginx
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - app
    ports:
      - "8080:80"
    networks:
      - node_network
  app:
    build: 
      context: app
    networks:
      - node_network
    tty: true
    container_name: appnode
    restart: on-failure
    ports:
      - "3000:3000"
    depends_on:
      - check-db-started
  check-db-started: 
    container_name: dockerize
    image: jwilder/dockerize:0.6.1
    depends_on:
        db:
          condition: service_healthy
    command: 'dockerize -wait=tcp://db:3306'
    networks:
      - node_network
networks:
  node_network:
    driver: bridge